version: '3'

services:
  watchtower:
      image: containrrr/watchtower
      container_name: watchtower
      volumes: /var/run/docker.sock:/var/run/docker.sock
      command: --schedule "* * * * *"

  projet-devops:
    image: alexkhoury/projet-devops
    container_name: projet-devops
    restart: always
    ports: "3000:3000"