name: CI

on:
  push : 
    branches:
      - 'main'

jobs:

  build-test-publish:
    runs-on: ubuntu-latest
    steps:

      - name : Build Docker Image
        run: sudo docker build -t alexkhoury/projet-devops ./frontend

      # - name: Run tests
      #   run: npm test

      # - name : Login to Docker Hub
      #   run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name : Push Docker Image
        run: docker push alexkhoury/frontend-ico