name: CI

on:
  push : 
    branches:
      - 'main'

jobs:

  build-test-publish:
    runs-on: ubuntu-latest
    steps:

      - name: Dockerise set-up
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: alexkhoury/projet-devops:latest #Test

      # - name: Log in to Docker Hub
      #   run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # - name : Build Docker Image
      #   run: sudo docker build -t alexkhoury/projet-devops --file ../frontend/Dockerfile .

      # # - name: Run tests
      # #   run: npm test

      # - name : Push Docker Image
      #   run: docker push alexkhoury/projet-devops