name: CI

on:
  push : 
    branches:
      - 'main'

jobs:

  build-test-publish:
    runs-on: ubuntu-latest
    steps:

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name : Build Docker Image
        run: docker build -t alexkhoury/projet-devops --file /Dockerfile .

      # - name: Run tests
      #   run: npm test

      - name : Push Docker Image
        run: docker push alexkhoury/projet-devops