name: CI

on:
  push : 
    branches:
      - 'main'

jobs:

  build-test-publish:
    runs-on: ubuntu-latest
    steps:

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name : Build Docker Image
        run: docker build -t alexkhoury/projet-devops --file Dockerfile ./frontend

      # - name: Run tests
      #   run: npm test

      # - name : Login to Docker Hub
      #   run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name : Push Docker Image
        run: docker push alexkhoury/frontend-ico